[package]
name = "pyglam"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyglam"
crate-type = ["cdylib", "rlib"]

[dependencies]
either = "~1.15"
pyo3 = { version = "~0.27", features = ["either"] }
glam = "~0.30"
# bin/stub_gen deps
env_logger = "~0.11"
pyo3-stub-gen = { version = "~0.17", features = ["either"] }
